name: workflow for sotring cache
on:
    workflow_dispatch:
jobs:
    cache-version:
        runs-on: ubuntu-latest
        steps:
            - name: Npm install
              uses: actions/setup-node@v3
              with:
                    node-version: '16'  
            - run: npm install axios
            - name: Cache node module
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
