name: called-wf
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input name
        run: echo "Hello, ${{ inputs.name }}"
      - name: secret
        run: echo "Secret is ${{ secrets.GITHUB_TOKEN }}"
      - name: user, repo and branch name
        run: echo "User is ${{ github.repository_owner }}, repo is ${{ github.event.repository.name }}, branch is ${{ github.ref_name }}"