name: caller workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'
jobs:
  call-workflow:
    uses: omomomomomom/1st-repo/.github/workflows/called-wf.yaml@new-branch
    with:
      name: ${{ github.event.inputs.name }}
    secrets:
      SECRETE_REPO: ${{ secrets.REPO_SECRETE }}